### ISSUE TITLE
Timeouts are too confusing

### ISSUE THREAD

**Issue by atdrendel** [shareup/phoenix-apple#11]
The word "timeout" means many different things in the project. For example, in `Channel`, the word "timeout" seems to refer to a backoff before trying to reconnect as opposed to a something like a network timeout. Let's be clearer with naming.

Additionally, there may be too many different kinds of timeouts in the project. `ChannelPush.timeout`, `Socket.timeout`, `Error.joinTimeout` `Socket.heartbeatTimeout`. They might all be needed, but it would be good to reduce their number, if possible.

- [x] Differentiate between timeout and backoff
- [x] Reduce the number of different kinds of "timeouts", if possible.

**Comment by myobie** [comment]
The name of [`Channel.timeout`](https://github.com/shareup/phoenix-apple/blob/3d8fa08d88f28fe7936b3ce75f6e15d5061d035f/Sources/Phoenix/Channel.swift#L25) is the same as what [the javascript uses](https://github.com/phoenixframework/phoenix/blob/925512895b3e30022ec21e3281551b8659714e50/assets/js/phoenix.js#L371) and should be used currently for the same purpose. The problem could be that in javascript one uses `setTimeout` and so they might mean "delay" or even just "span of time" instead of timeout. I do think we should like to the javascript if we do rename something so it's clear what it's other side is.

**Comment by atdrendel** [comment]
That makes sense. The other alternative would be to add `///` documentation to our types to describe their purpose more accurately. I'll try that first in order to keep the naming as similar as possible across our implementation and the canonical JavaScript implementation.

**Comment by atdrendel** [comment]
This has been resolved by https://github.com/shareup/phoenix-apple/pull/2. Specifically, I added [comments describing the meanings of the cases of `Channel.JoinTimer`](https://github.com/shareup/phoenix-apple/pull/2/files#diff-885d9d686dfb192301a6f15760c61398R4), which helped clarify the meaning of the join and rejoin timeouts.
